#pragma once
#ifndef QNPBMZHJKVERHBNRTJZMVSAQXTDLDPQQCDLVJYJLMGZUKASVSBJSAHHFTCPTPA
#define QNPBMZHJKVERHBNRTJZMVSAQXTDLDPQQCDLVJYJLMGZUKASVSBJSAHHFTCPTPA
#ifndef VERSION_INFO
#define VERSION_INFO 1.1.9
#endif
#define TOSTRING(x) #x
#define VERSION_INFO_STR(x) TOSTRING(x)
#endif
